AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 140

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 20

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: false

# Mixing the styles looks just silly.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Check with yard instead.
Style/Documentation:
  Enabled: false

# Disable adding a comment to enable frozen string
Style/FrozenStringLiteralComment:
  Enabled: false
