require 'parsley_simple_form/validators/base'
require 'parsley_simple_form/validators/presence'
require 'parsley_simple_form/validators/length'
require 'parsley_simple_form/validators/numericality'
require 'parsley_simple_form/validators/inclusion'
require 'parsley_simple_form/validators/exclusion'
require 'parsley_simple_form/validators/format'
require 'parsley_simple_form/validators/uniqueness'
